// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static SeleaDent.Web.Controllers.AccountController Account = new SeleaDent.Web.Controllers.T4MVC_AccountController();
    public static SeleaDent.Web.Controllers.BaseController Base = new SeleaDent.Web.Controllers.T4MVC_BaseController();
    public static SeleaDent.Web.Controllers.BugetController Buget = new SeleaDent.Web.Controllers.T4MVC_BugetController();
    public static SeleaDent.Web.Controllers.HomeController Home = new SeleaDent.Web.Controllers.T4MVC_HomeController();
    public static SeleaDent.Web.Controllers.OrganizationController Organization = new SeleaDent.Web.Controllers.T4MVC_OrganizationController();
    public static SeleaDent.Web.Controllers.UserController User = new SeleaDent.Web.Controllers.T4MVC_UserController();
    public static T4MVC.ModalsController Modals = new T4MVC.ModalsController();
    public static T4MVC.PagesController Pages = new T4MVC.PagesController();
    public static T4MVC.PartialController Partial = new T4MVC.PartialController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bloodhound_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bloodhound.min.js") ? Url("bloodhound.min.js") : Url("bloodhound.js");
        public static readonly string bloodhound_min_js = Url("bloodhound.min.js");
        public static readonly string bootstrap_clockpicker_min_js = Url("bootstrap-clockpicker.min.js");
        public static readonly string bootstrap_datepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-datepicker.min.js") ? Url("bootstrap-datepicker.min.js") : Url("bootstrap-datepicker.js");
        public static readonly string bootstrap_datepicker_min_js = Url("bootstrap-datepicker.min.js");
        public static readonly string bootstrap_datetimepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-datetimepicker.min.js") ? Url("bootstrap-datetimepicker.min.js") : Url("bootstrap-datetimepicker.js");
        public static readonly string bootstrap_datetimepicker_min_js = Url("bootstrap-datetimepicker.min.js");
        public static readonly string bootstrap_dialog_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-dialog.min.js") ? Url("bootstrap-dialog.min.js") : Url("bootstrap-dialog.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string clockpicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/clockpicker.min.js") ? Url("clockpicker.min.js") : Url("clockpicker.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class common {
            public const string UrlPath = "~/Scripts/common";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ajax.min.js") ? Url("ajax.min.js") : Url("ajax.js");
            public static readonly string Utils_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Utils.min.js") ? Url("Utils.min.js") : Url("Utils.js");
        }
    
        public static readonly string daterangepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/daterangepicker.min.js") ? Url("daterangepicker.min.js") : Url("daterangepicker.js");
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_12_4_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.12.4.intellisense.min.js") ? Url("jquery-1.12.4.intellisense.min.js") : Url("jquery-1.12.4.intellisense.js");
        public static readonly string jquery_1_12_4_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.12.4.min.js") ? Url("jquery-1.12.4.min.js") : Url("jquery-1.12.4.js");
        public static readonly string jquery_1_12_4_min_js = Url("jquery-1.12.4.min.js");
        public static readonly string jquery_1_12_4_min_map = Url("jquery-1.12.4.min.map");
        public static readonly string jquery_ui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-ui.min.js") ? Url("jquery-ui.min.js") : Url("jquery-ui.js");
        public static readonly string jquery_notifyBar_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.notifyBar.min.js") ? Url("jquery.notifyBar.min.js") : Url("jquery.notifyBar.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.bootstrap.min.js") ? Url("jquery.validate.unobtrusive.bootstrap.min.js") : Url("jquery.validate.unobtrusive.bootstrap.js");
        public static readonly string jquery_validate_unobtrusive_bootstrap_min_js = Url("jquery.validate.unobtrusive.bootstrap.min.js");
        public static readonly string jquery_validate_unobtrusive_bootstrap_min_js_map = Url("jquery.validate.unobtrusive.bootstrap.min.js.map");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string knockout_3_4_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout-3.4.2.min.js") ? Url("knockout-3.4.2.min.js") : Url("knockout-3.4.2.js");
        public static readonly string knockout_mapping_latest_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout.mapping-latest.debug.min.js") ? Url("knockout.mapping-latest.debug.min.js") : Url("knockout.mapping-latest.debug.js");
        public static readonly string knockout_mapping_latest_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout.mapping-latest.min.js") ? Url("knockout.mapping-latest.min.js") : Url("knockout.mapping-latest.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Modals {
            public const string UrlPath = "~/Scripts/Modals";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string SaveBugetCategoryViewModel_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/SaveBugetCategoryViewModel.min.js") ? Url("SaveBugetCategoryViewModel.min.js") : Url("SaveBugetCategoryViewModel.js");
        }
    
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string moment_with_locales_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment-with-locales.min.js") ? Url("moment-with-locales.min.js") : Url("moment-with-locales.js");
        public static readonly string moment_with_locales_min_js = Url("moment-with-locales.min.js");
        public static readonly string moment_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment.min.js") ? Url("moment.min.js") : Url("moment.js");
        public static readonly string moment_min_js = Url("moment.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Pages {
            public const string UrlPath = "~/Scripts/Pages";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string BugetPage_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/BugetPage.min.js") ? Url("BugetPage.min.js") : Url("BugetPage.js");
            public static readonly string LoggedUserVM_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/LoggedUserVM.min.js") ? Url("LoggedUserVM.min.js") : Url("LoggedUserVM.js");
            public static readonly string LoginPage_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/LoginPage.min.js") ? Url("LoginPage.min.js") : Url("LoginPage.js");
            public static readonly string MainViewModel_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/MainViewModel.min.js") ? Url("MainViewModel.min.js") : Url("MainViewModel.js");
        }
    
        public static readonly string sammy_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/sammy.min.js") ? Url("sammy.min.js") : Url("sammy.js");
        public static readonly string semantic_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/semantic.min.js") ? Url("semantic.min.js") : Url("semantic.js");
        public static readonly string semantic_min_js = Url("semantic.min.js");
        public static readonly string toastrModule_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/toastrModule.min.js") ? Url("toastrModule.min.js") : Url("toastrModule.js");
        public static readonly string typeahead_jquery_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/typeahead.jquery.min.js") ? Url("typeahead.jquery.min.js") : Url("typeahead.jquery.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_theme_min_css_map = Url("bootstrap-theme.min.css.map");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string bootstrap_min_css_map = Url("bootstrap.min.css.map");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Pages {
            public const string UrlPath = "~/Content/Pages";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string Header_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Header.min.css") ? Url("Header.min.css") : Url("Header.css");
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class common 
            {
                public static class Assets
                {
                    public static readonly string ajax_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/common/ajax.js"); 
                    public static readonly string Utils_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/common/Utils.js"); 
                }
            }
            public static partial class Modals 
            {
                public static class Assets
                {
                    public static readonly string SaveBugetCategoryViewModel_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/Modals/SaveBugetCategoryViewModel.js"); 
                }
            }
            public static partial class Pages 
            {
                public static class Assets
                {
                    public static readonly string BugetPage_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/Pages/BugetPage.js"); 
                    public static readonly string LoggedUserVM_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/Pages/LoggedUserVM.js"); 
                    public static readonly string LoginPage_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/Pages/LoginPage.js"); 
                    public static readonly string MainViewModel_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/Pages/MainViewModel.js"); 
                }
            }
            public static class Assets
            {
                public static readonly string bloodhound_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bloodhound.js"); 
                public static readonly string bloodhound_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bloodhound.min.js"); 
                public static readonly string bootstrap_clockpicker_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-clockpicker.min.js"); 
                public static readonly string bootstrap_datepicker_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datepicker.js"); 
                public static readonly string bootstrap_datepicker_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datepicker.min.js"); 
                public static readonly string bootstrap_datetimepicker_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datetimepicker.js"); 
                public static readonly string bootstrap_datetimepicker_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datetimepicker.min.js"); 
                public static readonly string bootstrap_dialog_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-dialog.js"); 
                public static readonly string bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.js"); 
                public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.min.js"); 
                public static readonly string clockpicker_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/clockpicker.js"); 
                public static readonly string daterangepicker_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/daterangepicker.js"); 
                public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.10.2.intellisense.js"); 
                public static readonly string jquery_1_12_4_intellisense_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.12.4.intellisense.js"); 
                public static readonly string jquery_1_12_4_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.12.4.js"); 
                public static readonly string jquery_1_12_4_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.12.4.min.js"); 
                public static readonly string jquery_ui_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-ui.js"); 
                public static readonly string jquery_notifyBar_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.notifyBar.js"); 
                public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.js"); 
                public static readonly string jquery_validate_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.min.js"); 
                public static readonly string jquery_validate_unobtrusive_bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.bootstrap.js"); 
                public static readonly string jquery_validate_unobtrusive_bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.bootstrap.min.js"); 
                public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.js"); 
                public static readonly string jquery_validate_unobtrusive_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.min.js"); 
                public static readonly string knockout_3_4_2_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/knockout-3.4.2.js"); 
                public static readonly string knockout_mapping_latest_debug_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/knockout.mapping-latest.debug.js"); 
                public static readonly string knockout_mapping_latest_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/knockout.mapping-latest.js"); 
                public static readonly string modernizr_2_6_2_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/modernizr-2.6.2.js"); 
                public static readonly string moment_with_locales_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment-with-locales.js"); 
                public static readonly string moment_with_locales_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment-with-locales.min.js"); 
                public static readonly string moment_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment.js"); 
                public static readonly string moment_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment.min.js"); 
                public static readonly string sammy_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/sammy.js"); 
                public static readonly string semantic_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/semantic.js"); 
                public static readonly string semantic_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/semantic.min.js"); 
                public static readonly string toastrModule_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/toastrModule.js"); 
                public static readonly string typeahead_jquery_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/typeahead.jquery.js"); 
            }
        }
        public static partial class Content 
        {
            public static partial class Pages 
            {
                public static class Assets
                {
                    public static readonly string Header_css = T4MVCHelpers.ProcessAssetPath("~/Content/Pages/Header.css");
                }
            }
            public static class Assets
            {
                public static readonly string bootstrap_theme_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-theme.css");
                public static readonly string bootstrap_theme_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-theme.min.css");
                public static readonly string bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.css");
                public static readonly string bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.min.css");
                public static readonly string Site_css = T4MVCHelpers.ProcessAssetPath("~/Content/Site.css");
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


