//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleaDent.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugetCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BugetCategory()
        {
            this.CategoryEntries = new HashSet<CategoryEntry>();
        }
    
        public long Id { get; set; }
        public long OrganizationId { get; set; }
        public string Name { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Status { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryEntry> CategoryEntries { get; set; }
    }
}
