//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleaDent.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryEntry()
        {
            this.CategoryEntryCosts = new HashSet<CategoryEntryCost>();
        }
    
        public long Id { get; set; }
        public long CategoryId { get; set; }
        public string Name { get; set; }
        public double Total { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Status { get; set; }
    
        public virtual BugetCategory BugetCategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryEntryCost> CategoryEntryCosts { get; set; }
    }
}
