//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleaDent.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryEntryCost
    {
        public long Id { get; set; }
        public long CategoryEntryId { get; set; }
        public double Cost { get; set; }
        public System.DateTime Date { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Status { get; set; }
    
        public virtual CategoryEntry CategoryEntry { get; set; }
        public virtual User User { get; set; }
    }
}
